# Generated by Django 4.1.1 on 2022-09-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=30)),
                ('apellido_alumno', models.CharField(max_length=30)),
                ('telefono_alumno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=30)),
                ('modulos', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='asignatura_de_alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=30)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
    ]
